### ISSUE TITLE
No longer works

### ISSUE THREAD

**Issue by StylinGreymon** [f0rki/mpd-album-shuffle#1]
not sure when it stopped working but now when I run
`python mpd-album-shuffle.py sort`
I get this error:
```
Traceback (most recent call last):
  File "mpd-album-shuffle.py", line 240, in <module>
    sys.exit(main())
  File "mpd-album-shuffle.py", line 226, in main
    al = AlbumList(client)
  File "mpd-album-shuffle.py", line 79, in __init__
    self.refresh()
  File "mpd-album-shuffle.py", line 89, in refresh
    self.albums.add(song["album"])
TypeError: unhashable type: 'list'
```

**Comment by f0rki** [comment]
@StylinGreymon are there any songs with multiple albums in your playlist? Maybe the mpd API has changed. I don't know. To be honest, I don't use this script, or mpd for that matter, anymore.

Anyway I just pushed a small fix. Can you check whether it works now?

**Comment by StylinGreymon** [comment]
all fixed up, thank you!
