### ISSUE TITLE
add to pypi

### ISSUE THREAD

**Issue by ddffnn** [f0rki/mpd-album-shuffle#2]
Would you consider adding this to pypi for easier installation?

**Comment by f0rki** [comment]
I am neither using nor actively maintaining this anymore. I am somewhat surprised this still works to be honest. I'll merge pull requests though. Maybe I'll take a look at pushing this to pypi, but I'm not sure doing so is that useful? 🤔

On 10 March 2020 19:17:35 CET, ddffnn <notifications@github.com> wrote:
>Would you consider adding this to pypi for easier installation?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/f0rki/mpd-album-shuffle/issues/2

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by f0rki** [comment]
I added a `setup.py`, so this is now pip-installable. However, I don't think I'll bother with pypi.
